スワップ範囲内のオブジェクトにハイライトを実装
Twilight-Studioo/production pull request #148
Opened 2024-09-13 09:54 UTC by Hayato222

## やったこと
・SwapModel,SwapPresenter,SwapViewにそれぞれハイライトのためのコードの実装
・MainControllerでSwapPresenterに追加した処理を呼び出し
・リムの処理が同じなのでSwapViewのSetHightlightの中身をコメントアウト中

2024-09-14 07:02 UTC, Matuyuhi commented
切った時のdevelopがだいぶ古そうです

2024-09-15 16:05 UTC, ichiharayuuma commented
LGTM

2024-09-17 03:28 UTC, Matuyuhi requested changes
アニメーションのmeta削除されていたり、移動されていたりするのが気になります

2024-09-17 03:28 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/View/SwapView.cs
> +            //     material.SetFloat("_RimThreashould", 1);
コメントアウトは全部削除で
関数自体も不要なら削除

2024-09-17 08:24 UTC, Matuyuhi reviewed
animationのmetaの変更はguidが変更されていますが、guidの変更はunityが勝手に修正しているはずなので大丈夫だと思います。おそらく

2024-09-17 08:26 UTC, Matuyuhi approved these changes
🙆

2024-09-18 08:37 UTC, merged