選択しているオブジェクトにエフェクトを実装
Twilight-Studioo/production pull request #159
Opened 2024-09-17 05:56 UTC by Hayato222

## やった事

スワップするオブジェクトを選択したときにエフェクトが流れるようにした。

## Related Issue
- close #~~

## 動作確認

## レビューしてほしいこと
- [ ]

## 備考

-

2024-09-20 08:52 UTC, Matuyuhi requested changes

2024-09-20 08:52 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Presenter/SwapPresenter.cs
> -                swapItemViews[item.Value.Id].OnDeselected();
なるべく既存の実装は残す形で

2024-09-22 16:22 UTC, Hayato222 commented on src/Assets/Scripts/Feature/Presenter/SwapPresenter.cs
> -                swapItemViews[item.Value.Id].OnDeselected();
他に消してあるOnDeselected OnSelected全部復活させておいたほうがいいですか？

2024-09-24 02:47 UTC, Matuyuhi approved these changes
LGTM 🍽️

2024-09-24 02:47 UTC, merged