Add EndScene
Twilight-Studioo/production pull request #176
Opened 2024-09-24 07:08 UTC by RaitoFs

## やった事

ゲームオーバー画面の実装

## Related Issue
- close #~~

## 動作確認

プレーヤーのhpは0になったら、ゲームオーバーのSceneに遷移

## レビューしてほしいこと
- [ ]

## 備考

-

2024-09-24 07:19 UTC, Matuyuhi requested changes
実装するの早いと思いました。👍 
全体的には良いと思いますが、
`EndField`辺りの処理が、`GameObject.Find()`で取得して使っているので、`playerModel`や`playerPresenter`に追加せず、新しくクラスを作って`playerHpBar.UpdateHealthBar`をSubscribeするような形が綺麗だと思います！

2024-09-24 07:19 UTC, Matuyuhi commented on src/ProjectSettings/EditorBuildSettings.asset
> +    guid: b3a67ad083c404e138eebb789656742d
追加ありがとうございます！(まだ使うシーンが未定なので今のTemplateStageのままで良いと思ってます。)

2024-09-24 09:25 UTC, RaitoFs commented on src/ProjectSettings/EditorBuildSettings.asset
> +    guid: b3a67ad083c404e138eebb789656742d
了解です！後直します。

2024-09-27 09:56 UTC, Matuyuhi commented
@RaitoFs 
`EndFieldController`クラスがあるファイルをpushし忘れてると思います〜(CIでもそんな意味のエラーが出てる)

2024-09-30 09:07 UTC, RaitoFs commented
すみません！もう一回pushしました。確認お願いします。

2024-10-01 02:20 UTC, Matuyuhi requested changes
@RaitoFs 
- ゲーム画面の`EndField`をPrefabs/System/Canvas.prefabに追加
- `EndField`のサイズ->16:9aspect対応

2024-10-04 05:19 UTC, ichiharayuuma commented
これはマージして大丈夫ですか？

2024-10-19 12:04 UTC, Matuyuhi approved these changes
気になるところ修正したのでマージ

2024-10-19 12:04 UTC, merged