voltage機能を実装
Twilight-Studioo/production pull request #75
Opened 2024-08-19 15:16 UTC by Hayato222

## 追加項目
Script/Feature/View/VoltageView.csを追加

## 実装
スワップ時にボルテージをチャージ
アタック時に既定のボルテージ量に達していたら攻撃力アップ
ボルテージのチャージ量、アタック時の使用量、攻撃の強化倍率をインスペクターで調整できるように実装

2024-08-20 15:03 UTC, Matuyuhi requested changes
今回、新規でscript作成していますがMonoBehaviour必須の処理がなく、playerに付随する処理なので、playerModelなどに直接implするのが良いです。
その方が、別シーンへの適応の手間もなくなるので。

2024-08-20 15:03 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
> +        private VoltageView voltageView;
コンストラクタでしかsetしないのでreadonlyにできます

2024-08-21 12:02 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/View/VoltageView.cs
> +            Debug.Log("Swap voltage : "+ voltageValue);
何かしら画面に数値とか出しちゃっても良いと思います

2024-08-27 09:53 UTC, ichiharayuuma commented
マージしようとしたんですがどうしても PlayerModel でエラーが出てしまうのでこっちにいったん develop をマージして直してもらってからマージしようと思います。

見たところ、6行目の
~~~
using Feature.View
~~~
で Feature.View を見つけられなくとエラーになっているようです。

2024-09-05 23:50 UTC, Matuyuhi commented
コンフリクトしてます

2024-09-06 01:38 UTC, Matuyuhi requested changes
レビューしました。

2024-09-06 01:38 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Model/Feature.Model.asmdef
> +        "GUID:058b96cf72d1b46bb8a5e894741cbe18"
Viewが必要な処理は別のクラスに渡して欲しいです。
Modelの機能は状態の保持とそれに関連する`Modelで完結している処理`のみで完結させたいです。

2024-09-06 01:38 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Component/VoltageBar.cs
> +            Debug.Log(characterParams.voltageValue);
[MUST]
logは削除

2024-09-06 01:38 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Model/PlayerModel.cs
> +            characterParams.voltageValue = Mathf.Clamp(characterParams.voltageValue, MINVOLTAGEVALUE, MAXVOLTAGEVALUE);
characterParams(ScriptableObject)はruntimeで変更を加えないようにして欲しいです
他のパラメーターもそうですが、Model内に変数を持たせていると思います。

2024-09-06 01:38 UTC, Matuyuhi commented on src/Assets/Scripts/Feature/Component/VoltageBar.cs
> +    public class VoltageBar :MonoBehaviour
[CAN]
このクラスの実装はGameUiView内に実装できそうなので不要になるかも

2024-09-10 14:54 UTC, merged